### ISSUE TITLE
LinkedIn PR refinements

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/kratos#7]
## 
As a user I want to be able to login using LinkedIn

##  Acceptance criteria
- [x] Address PR feedback from Ory 
- [x] Investigate further issues still open

**Comment by valentinyanakiev** [comment]
- Updated the PR, addressed the feedback
- Introduced global HTTP client for all API calls
- Addressed styling issues / PR feeback, simplifying error handling + json unmarshalling 
- Split the different calls into their own methods, making the flow very explicit
- Updated the claims response - now LocalizedFirstName maps to GivenName in the claims object, not to Name. LocalizedFirstName + ' ' + LocalizedLastName maps to name
- Updated tests
- Refreshed the PR to have our issues references via their GitHub links, making them publicly accessible
- Updated our blocking issues with some details / clues
- Investigated whether the issue was with the http client I was using - it was not, unfortunately
